#!/usr/bin/env python3
"""
PyTorch Geometric Data Loader for PyG 1.x versions
Specifically designed for compatibility with PyG 1.x (e.g., PyG 1.7.2)

Use this loader when working with PyG 1.x environments (e.g., openabc conda env)

Special Feature:
- Supports loading PT files generated by PyG 2.x (backward compatibility)
- Automatically converts PyG 2.x data format to PyG 1.x compatible format
"""

import torch
import pickle
from typing import Optional, Any, List


def _is_pyg2_data(data: Any) -> bool:
    """
    Detect if loaded data is from PyG 2.x format

    Args:
        data: Loaded data object

    Returns:
        True if data is PyG 2.x format
    """
    # PyG 2.x uses _store._mapping structure
    if hasattr(data, '_store') and hasattr(data._store, '_mapping'):
        return True
    return False


def _convert_pyg2_to_pyg1(data: Any) -> Any:
    """
    Convert PyG 2.x Data object to PyG 1.x compatible format

    Args:
        data: PyG 2.x Data object

    Returns:
        PyG 1.x compatible Data object
    """
    try:
        from torch_geometric.data import Data
    except ImportError:
        # If PyG not available, return as-is
        return data

    # Extract all attributes from PyG 2.x _store._mapping
    attrs = {}
    if hasattr(data, '_store') and hasattr(data._store, '_mapping'):
        mapping = data._store._mapping
        for key, value in mapping.items():
            attrs[key] = value

    # Create new PyG 1.x Data object with extracted attributes
    converted_data = Data(**attrs)

    return converted_data


def load_pyg_data_v1(
    file_path: str,
    map_location: str = 'cpu',
    extract_attrs: Optional[List[str]] = None
) -> Any:
    """
    Load PyG Data object compatible with PyG 1.x versions

    Special handling:
    - Automatically detects and converts PyG 2.x format data
    - Ensures backward compatibility when loading newer PT files

    Args:
        file_path: Path to .pt file
        map_location: Device location ('cpu' or 'cuda')
        extract_attrs: Optional list of attributes to extract

    Returns:
        PyG Data object or attribute dictionary
    """
    # Load without weights_only parameter (not available in old PyTorch)
    try:
        data = torch.load(file_path, map_location=map_location)
    except Exception as e:
        raise Exception(f"Failed to load {file_path}: {e}")

    # Check if data is from PyG 2.x and convert if necessary
    if _is_pyg2_data(data):
        print(f"Detected PyG 2.x format data, converting to PyG 1.x format...")
        data = _convert_pyg2_to_pyg1(data)

    # If extract_attrs is provided, extract specific attributes
    if extract_attrs is not None:
        result = {}
        for attr_name in extract_attrs:
            result[attr_name] = extract_pyg_attr_v1(data, attr_name)
        return result

    return data


def extract_pyg_attr_v1(data: Any, attr_name: str, default: Any = None) -> Any:
    """
    Extract attribute from PyG 1.x Data object

    Args:
        data: PyG Data object
        attr_name: Attribute name to extract
        default: Default value if extraction fails

    Returns:
        Attribute value or default value
    """
    # Method 1: Try direct attribute access (PyG 1.x style)
    try:
        return getattr(data, attr_name)
    except Exception:
        pass

    # Method 2: Try __dict__ access
    try:
        if hasattr(data, '__dict__') and attr_name in data.__dict__:
            return data.__dict__[attr_name]
    except Exception:
        pass

    # Method 3: Try keys() if available
    try:
        if hasattr(data, 'keys') and attr_name in data.keys:
            return data[attr_name]
    except Exception:
        pass

    return default


def list_pyg_attributes_v1(data: Any) -> List[str]:
    """
    List all available attributes in a PyG 1.x Data object

    Args:
        data: PyG Data object

    Returns:
        List of attribute names
    """
    attrs = []

    # Try __dict__
    try:
        if hasattr(data, '__dict__'):
            attrs.extend(data.__dict__.keys())
    except Exception:
        pass

    # Try keys
    try:
        if hasattr(data, 'keys'):
            attrs.extend(data.keys)
    except Exception:
        pass

    # Remove duplicates and internal attributes
    attrs = list(set(attrs))
    attrs = [a for a in attrs if not a.startswith('_')]

    return sorted(attrs)


def save_pyg_data_v1(data: Any, file_path: str):
    """
    Save PyG Data object in PyG 1.x compatible format

    Args:
        data: PyG Data object
        file_path: Output file path
    """
    import os

    # Ensure output directory exists
    output_dir = os.path.dirname(file_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    # Save with protocol 4 for compatibility
    torch.save(data, file_path, pickle_protocol=4)


# Convenience aliases
load_compatible = load_pyg_data_v1
extract_attr = extract_pyg_attr_v1
list_attrs = list_pyg_attributes_v1
